site_name: Hooker
site_url: https://khulnasoft-lab.github.io/hooker
site_description: Integrate vulnerability scanning with a variety of systems.
docs_dir: docs/
repo_name: Hooker
repo_url: https://github.com/khulnasoft-lab/hooker
edit_uri: ""
copyright: Copyright 2019-2022 Khulnasoft Security Software Ltd.

nav:
- Introduction: index.md
- Use cases:
  - Simple Examples: examples.md
  - Blueprints:
    - Vul Scan: blueprints/vul-vulnerability-scan.md
    - Vul AWS Security Hub: blueprints/vul-aws-security-hub.md
    - Vul Operator: blueprints/vul-operator.md
    - Pagerduty: blueprints/devops-pagerduty.md
    - Others:
      - External Healthcheck: blueprints/external-healthcheck.md
      - Image Processing: blueprints/image-processing.md
- Installation: install.md
- Configuration:
  - Config File: config.md
  - General: settings.md
  - Routes: routes.md
  - Templates: templates.md
  - Actions: actions.md
  - Controller/Runner: controller-runner.md
- Demo: demo.md
- Khulnasoft Cloud: khulnasoftcloud.md
- Hooker UI: ui.md
- Advanced: advanced.md

theme:
  name: material
  custom_dir: overrides
  language: 'en'
  logo: img/hooker.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


markdown_extensions:
- pymdownx.highlight
- pymdownx.details
- pymdownx.superfences
- admonition
- attr_list
- md_in_html
- toc:
    permalink: true

# All data defined under extra is automatically exposed as a variable and can
# be used from the template. For example, {{ var.version }}.
#
# Requires pip install mike and pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/khulnasoft-lab
  - icon: fontawesome/brands/slack
    link: https://slack.khulnasoft.com/
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/channel/UCZd5NF4XJRaU-yfextsY-pw
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/KhulnaSoftTeam
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/khulnasoftteam/
  version:
    provider: mike

# Requires pip install mkdocs-macros-plugin
plugins:
- search
- macros
