{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim) }}
{{- $fullName := include "hooker.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    {{- include "hooker.labels" . | nindent 4 }}
  name: {{ include "hooker.fullname" . }}-pvc
spec:
  accessModes:
  {{- range .Values.persistentVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}
{{- end }}