actions:
  - type: awssecurityhub
    enable: true
    name: Send Findings to Security Hub
routes:
  - name: Send Vul Findings to AWS Security Hub
    template: raw-json
    actions:
      - Send Findings to Security Hub
    input-files:
      - Vul AWS Findings
templates:
  - name: raw-json
    rego-package: hooker.rawmessage.json
rules:
  - name: Vul AWS Findings
name: Send Vul Results to AWS Security Hub
