apiVersion: v1
kind: Service
metadata:
  name: {{ include "hooker.fullname" . }}
  labels:
    {{- include "hooker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.portSsl }}
      targetPort: {{ .Values.service.targetPortSsl }}
      protocol: TCP
      name: http-ssl
  selector:
    {{- include "hooker.selectorLabels" . | nindent 4 }}
