---
# This is a manually triggered workflow to build and publish the MkDocs from the
# specified Git revision to GitHub pages on https://khulnasoft-lab.github.io/hooker
name: Publish Documentation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to deploy, e.g. v0.0.1
        required: true

# Disable permissions granted to the GITHUB_TOKEN for all the available scopes.
permissions: {}

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}
        fetch-depth: 0
        persist-credentials: true
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: |
        pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        pip install mike
        pip install mkdocs-macros-plugin
      env:
        # Note: It is not the same as ${{ secrets.GITHUB_TOKEN }} !
        GH_TOKEN: ${{ secrets.MKDOCS_KHULNASOFT_BOT }}
    - run: |
        git config user.name "khulnasoft-bot"
        git config user.email "khulnasoft-bot@users.noreply.github.com"
    - run: |
        mike deploy --push --update-aliases ${{ github.event.inputs.ref }} latest